### ISSUE TITLE
use only team names in real_groups array

### ISSUE THREAD

**Issue by melkosoft** [n4bb12/verdaccio-github-oauth-ui#125]
## Feature Request
As I can see in log after authentication real_groups is filled with ALL organizations which are visible for me even though I am not a member of any teams there. It's not good. The purpose of organization is to restrict access only for users who are members of any team in organization. Go even further use team filter to allow only members of particular teams in organization. Using only **team_name** instead of **github/org_name/team_name** will help with access templates, something like this
```
packages:
   "@*/*":
      access: $authenticated
      publish: $groups
      unpublish: admin_group
```
In this case member of team "developers" will have publish access for "@developers/package_1" instead of name like: "@github/my-org/developers/package_1"
