### ISSUE TITLE
Plugin not detected when installed globally

### ISSUE THREAD

**Issue by ramadimasatria** [n4bb12/verdaccio-github-oauth-ui#13]
#### Versions

|                           | Version |
| ------------------------- | ------- |
| verdaccio                 |    3.8.5     |
| verdaccio-github-oauth-ui |    1.5.2     |

#### Expected behavior
I am planning to setup a verdaccio server in a VM. I installed verdaccio and verdaccio-github-oauth-ui globally using `npm i -g verdaccio verdaccio-github-oauth-ui`.

#### Observed behaviour
The `github-oauth-ui` plugin is not detected when I tried running `verdaccio`

#### Steps to reproduce
1. Install verdaccio & verdaccio-github-oauth-ui globally
2. Update config.yaml
3. Run `verdaccio`

#### Additional context
<img width="680" alt="screen shot 2018-11-01 at 12 46 46" src="https://user-images.githubusercontent.com/4123969/47835126-f2233900-ddd4-11e8-9113-88d3f7b7554e.png">

**Comment by juanpicado** [comment]
The error might depends of your nodejs set up. I would describe more about your environment otherwise the author of this plugin won’t be able to help you.

**Comment by juanpicado** [comment]
Configuration file also helps.

**Comment by ramadimasatria** [comment]
I use the LTS version of nodejs (v10.13.0) installed with nvm.
As for configuration, I changed the default config file on `~/.config/verdaccio/config.yaml` to match with what described on readme.

```
storage: ./storage
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  # enable: false
  title: Verdaccio

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

auth:
  github-oauth-ui:
    org: myorgname

middlewares:
  audit:
    enabled: true
  github-oauth-ui:
    client-id: myclientid
    client-secret: myclientsecret

logs:
  - {type: stdout, format: pretty, level: http}
```
