### ISSUE TITLE
Bug allowing anyone to log in as any valid GitHub user

### ISSUE THREAD

**Issue by Doridian** [n4bb12/verdaccio-github-oauth-ui#160]
### Versions

|             | Version |
| ----------- | ------- |
| Verdaccio   |    5.13     |
| This plugin |     5.0    |
| Node        |      Whatever Verdaccio 5.13 Docker image ships   |

Have htpasswd and this plugin enabled

### Observed behavior
Verdaccio lets you login with a GitHub user with any password
`npm adduser --registry https://xxxxxx`
Enter GitHub username of a user previously used with this plugin, enter ANY password.
You will get issued a token.

Logs show:
```
[github-oauth-ui] User successfuly authenticated: {
  name: 'USERNAME',
  groups: [ '$all', '@all', '$authenticated', '@authenticated' ],
  real_groups: [ whatever the actual GH user has, like orgs etc ]
}
```

### Expected behavior
Login failure

### Steps to reproduce
- Log in with any GitHub user into an instance with this plugin installed
- Run `npm adduser --registry https://xxxxxx` on any machine, with the correct username and any password

**Comment by n4bb12** [comment]
Please read the breaking changes https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/5.0.0

**Comment by Doridian** [comment]
I did not upgrade. I started on this version. I did not use any previous version of this plugin and followed the instructions in the docs folder.

**Comment by Doridian** [comment]
Also, even if I did upgrade, the breaking changes only mention permission issues.
This is NOT a permissions issue at all.
Under no circumstances should this plugin allow you to log in as someone else, who's credentials you do not have, which it does.

**Comment by Doridian** [comment]
@n4bb12 Please, if you think I did something wrong, tell me. But don't just close the issue assuming I upgraded from a previous version.

Here's my whole config, which seems correct from your docs folder:
```
# path to a directory with all packages
storage: /verdaccio/storage
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  github-oauth-ui:
    client-id: REDACTED
    client-secret: REDACTED
    token: REDACTED
  htpasswd:
    file: /verdaccio/conf/htpasswd
    algorithm: bcrypt
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    max_users: -1

packages:
  '@*/*':
    access: github/org/xxx xxx
    publish: github/org/xxx xxx

  '**':
    access: github/org/xxx xxx
    publish: github/org/xxx xxx

# To use `npm audit` uncomment the following section
middlewares:
  github-oauth-ui:
    enabled: true
  audit:
    enabled: true

security:
  api:
    jwt:
      sign:
        expiresIn: 90d
  web:
    sign:
      expiresIn: 7d

# log settings
log: { type: stdout, format: pretty, level: http }
```
