### ISSUE TITLE
Auth token remains valid after being revoked through the GitHub UI

### ISSUE THREAD

**Issue by micahbeech** [n4bb12/verdaccio-github-oauth-ui#176]
# Bug Report

## Versions

|             | Version |
| ----------- | ------- |
| Verdaccio   | 5.19.1  |
| This plugin | 6.0.1   |
| Node        | 18.12.1 |

## Observed behavior

When revoking tokens following the instructions under https://github.com/n4bb12/verdaccio-github-oauth-ui/blob/master/docs/configuration.md#revoking-tokens, it appears as though the token remains valid despite it being revoked.

Once I have revoked a token, I can continue to browse packages and their versions in the Web UI, pull packages via the command line, and publish new packages. It's only once I logout of the Verdaccio UI or clear my local token (i.e. I'm forced to generate a new one) that my requests are rejected and I have to re-authorize the GitHub app.

I have tried invalidating tokens a few ways, namely

1. Revoking a single token, by logging into GitHub as the user who owns that token and clicking `Revoke`.
2. Revoking all tokens, by logging into GitHub as the Org owner and clicking `Revoke all user tokens`.
3. Rotating the secret for the OAuth app.
   - In my eyes, this was a last resort since 1 and 2 are the documented methods (as per the above link), but it seemed like a surefire approach since changing the secret should mean that all JWTs signed with the old secret become invalid. To me, this implies that each request is not being verified against the secret currently provided in the config.

Note: I _am_ seeing requests getting rejected after a token expires. However, I need to maintain long-lasting tokens for CI builds, and therefore need a reliable way to revoke them should they be compromised.

## Expected behavior

After revoking a token, it should no longer be able to access or publish packages in Verdaccio.

## Steps to reproduce

This can be reproduced via the Web UI or via the command line.

Web UI:

1. Log into Verdaccio and authorize the app via the GitHub OAuth flow.
2. Verify that you have view the appropriate packages once you are directed back to Verdaccio.
3. Go to GitHub `Settings > Applications > Authorized OAuth Apps` and revoke Verdaccio.
4. Verify that you are still able to browse packages on the Web UI.

Command line:

1. Run `npx verdaccio-github-oauth-ui --registry https://my.registry` and authorize Verdaccio.
2. Publish a package to the registry.
3. Go to GitHub `Settings > Applications > Authorized OAuth Apps` and revoke Verdaccio.
4. Verify that you are still able to publish packages.

## Additional context

Dockerfile:

```Dockerfile
ARG VERDACCIO_TAG
FROM verdaccio/verdaccio:${VERDACCIO_TAG}
USER root
ARG VERDACCIO_GITHUB_OAUTH_VERSION
RUN npm install --global verdaccio-github-oauth-ui@${VERDACCIO_GITHUB_OAUTH_VERSION}
USER verdaccio
```

Config:

```yaml
storage: /verdaccio/storage/data
max_body_size: 200mb
web:
  title: Verdaccio

middlewares:
  github-oauth-ui:
    enabled: true
  audit:
    enabled: true

auth:
  github-oauth-ui:
    org: my-org
    client-id: ${githubClientId}
    client-secret: ${githubClientSecret}
    token: ${githubToken}

uplinks:
  npmjs:
    url: https://registry.yarnpkg.com/
    cache: true
    maxage: 2h
    agent_options:
      keepAlive: true
      maxSockets: 40
      maxFreeSockets: 10

packages:
  "**":
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

security:
  api:
    legacy: false
    jwt:
      sign:
        expiresIn: 365d
  web:
    sign:
      expiresIn: 365d

user_agent: true

logs: { type: stdout, format: json, level: http }
```
