### ISSUE TITLE
jwt error and login stay as basic auth form

### ISSUE THREAD

**Issue by idangozlan** [n4bb12/verdaccio-github-oauth-ui#20]
#### Versions

|                           | Version |
| ------------------------- | ------- |
| verdaccio                 |       4.0.4  |
| verdaccio-github-oauth-ui |   1.7.3      |

#### Expected behavior
When clicking on Login, it should take to the auth page.

#### Observed behaviour
The login button leads to the regular login form.
When manually pointed to http://0.0.0.0:4873/-/oauth/authorize/ , it's authorized me on GitHub and then on callback, I've got the following error:
```
 http <-- 302, user: null(127.0.0.1), req: 'GET /-/oauth/authorize', bytes: 0/364
 error--- unexpected error: this.auth.issueUIjwt is not a function
TypeError: this.auth.issueUIjwt is not a function
    at Callback.<anonymous> (/Users/aaa/.nvm/versions/node/v8.15.0/lib/node_modules/verdaccio-github-oauth-ui/dist/server/plugin/Callback.js:54:49)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/aaa/.nvm/versions/node/v8.15.0/lib/node_modules/verdaccio-github-oauth-ui/dist/server/plugin/Callback.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
 http <-- 500, user: null(127.0.0.1), req: 'GET /-/oauth/callback?code=******', error: internal server error
```
and the response is:
```
{
error: "internal server error"
}
```

#### Steps to reproduce
1. npm i -g verdaccio
2. npm i -g verdaccio-github-oauth-ui
3. set configuration:
```
auth:
  github-oauth-ui:
    org: myorg # required, people within this org will be able to auth
middlewares:
  github-oauth-ui:
    client-id: myId # required
    client-secret: mySecret # required
```
