### ISSUE TITLE
auth config not picked up inside docker image

### ISSUE THREAD

**Issue by philip-lamb** [n4bb12/verdaccio-github-oauth-ui#202]
### Versions

|             | Version |
| ----------- | ------- |
| Verdaccio   |  [v6.1.1](https://github.com/verdaccio/verdaccio/releases/tag/v6.1.1)       |
| This plugin |   [v6.0.10](https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/6.0.10)      |
| Node        |   v23.10.0      |

### Environment

|                  | Name | Version |
| ---------------- | ---- | ------- |
| Package manager  |  npm    |         |
| Browser          |  N/A    |         |
| Operating system |  Mac OS    |   15.3.2      |

### Observed behavior

Running verdaccio in a docker image with verdaccio-github-oauth-ui plugin, the server starts and reads config, but fails with an error during launching of the plugin:

```
{"level":30,"time":1743369420323,"pid":121,"hostname":"SandboxHost-638789661559925807","file":"/verdaccio/conf/config.yaml","msg":"config file  - /verdaccio/conf/config.yaml"}
{"level":30,"time":1743369420402,"pid":121,"hostname":"SandboxHost-638789661559925807","name":"@verdaccio/local-storage","pluginCategory":"storage","msg":"plugin @verdaccio/local-storage successfully loaded (storage)"}
[github-oauth-ui] Version: verdaccio-github-oauth-ui@6.0.10
[github-oauth-ui] Invalid configuration at "auth.github-oauth-ui.client-id": Expected `value` to be of type `string` but received type `undefined` — Please check your verdaccio config.
```

If I remove the plugin altogether, the server launches using the config from my config.yaml, but without the GitHub auth.

### Expected behavior

Plugin should read config OK and start.

### Steps to reproduce

Dockerfile:
```
FROM verdaccio/verdaccio:latest
USER root
ENV NODE_ENV=production
RUN cd /usr/local/lib/node_modules/verdaccio \
  && npm install --global-style --no-bin-links --no-optional verdaccio-github-oauth-ui@latest
USER verdaccio
COPY verdaccio.yaml /verdaccio/conf/config.yaml
```

config.yaml:
```
listen:
  - 0.0.0.0:8443
https:
  # Self-signed certificate.
  key: /verdaccio/conf/verdaccio-key.pem
  cert: /verdaccio/conf/verdaccio-cert.pem
  ca: /verdaccio/conf/verdaccio-csr.pem
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins
log:
  type: stdout
  format: pretty
  level: info
server:
  keepAliveTimeout: 60
max_body_size: 1024mb
auth:
  github-oauth-ui:
    client-id: "0123456789abcdef"
    client-secret: "0123456789abcdef"
    token: "ghp_0123456789abcdef"
security:
  api:
    jwt:
      sign:
        expiresIn: 90d
  web:
    sign:
      expiresIn: 7d
middlewares:
  github-oauth-ui:
    enabled: true
  audit:
    enabled: true
packages:
  '**':
    # privileges are one of "publish:", "unpublish:", and "access:".
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: github/org/MYORG
    publish: github/org/MYORG
```

### Additional context
I have tried using both environment variables for the config values (client ID etc) and just having them as string literals in the config, without any change in the behaviour.
