### ISSUE TITLE
Can't seem to use login button?

### ISSUE THREAD

**Issue by aforty** [n4bb12/verdaccio-github-oauth-ui#39]
I'm not able to follow the setup instructions in the README. "Click the login button and get redirected to GitHub."

When I press the Login button top-right on the navbar I simply get the default username/password prompt. I am not forwarded to github. If I use the `npx` method it works but then I'm not logged into the website and can't browse packages visually.

```
# config.yaml

plugins: ./node_modules
storage: ./storage

auth:
  github-oauth-ui:
    org: foobarorg
    client-id: xxxx
    client-secret: yyyy

logs:
  - { type: stdout, format: pretty, level: http }

middlewares:
  audit:
    enabled: true
  github-oauth-ui:
    enabled: true
  https:
    enabled: true

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

web:
  enable: true
  title: "FooBar Registry"
  primary_color: "#525252"
  gravatar: true
  sort_packages: asc
```

```
# versions
  "verdaccio": "^4.4.0",
  "verdaccio-github-oauth-ui": "^2.2.1",
  "verdaccio-https": "^1.0.11",
  "verdaccio-s3-storage": "^0.2.1"
```
