### ISSUE TITLE
Does not work if you enable security.api.jwt tokens

### ISSUE THREAD

**Issue by dantman** [n4bb12/verdaccio-github-oauth-ui#48]
## Bug Report

When using the verdaccio-github-oauth-ui plugin auth is broken if you enable the [jwt setting](https://verdaccio.org/docs/en/configuration#security) but do not set `legacy: true` (i.e. you move to JWT instead of using the deprecated legacy signature).

#### Versions

|                           | Version |
| ------------------------- | ------- |
| verdaccio                 | 4.7.2 |
| verdaccio-github-oauth-ui | 2.2.4 |

#### Expected behavior

If JWT is enabled in the API then the npm tokens gh-oauth-ui generates should be JWT tokens, not legacy tokens.

#### Observed behaviour

I tried enabling the htaccess plugin alongside gh-oauth-ui and logging in with `npm login`. htaccess generates proper JWTs, so this is a gh-oauth-ui issue.

This appears to be the code generating the npm token (I searched around the codebase and followed the code to confirm this was the specific function called).

https://github.com/n4bb12/verdaccio-github-oauth-ui/blob/9740bc5f0d3812432cffb9bc3598ff49acdb9e83/src/server/verdaccio/Verdaccio.ts#L36-L38

#### Steps to reproduce
1. Use the following security settings:
  ```yaml
  security:
    api:
      jwt:
        sign:
          expiresIn: 90d
    web:
      sign:
        expiresIn: 7d
  ```
2. Sign in with GitHub
3. Follow the npm set token commands
4. Try publishing a package, it will fail because the token is a legacy token

**Comment by n4bb12** [comment]
Thank for the great description.

**Comment by n4bb12** [comment]
API JWT is supported with
https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/2.3.0

Thanks for reporting this 🤝

**Comment by dantman** [comment]
Thanks. However there may be a bug.

I am getting the error `user dantman is not allowed to publish package @company/package` when I use JWT but when I disable JWT and use a legacy token I can successfully publish a package.

Publishing this package only requires basic authentication.

```yaml
packages:
  '@company/*':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
```
